### ISSUE TITLE
调用gclient sync同步依赖时报错

### ISSUE THREAD

**Issue by archer-yq** [Natoto/flutterOnExistApp#8]
Running hooks:  28% ( 2/ 7) win_toolchain

running 'C:\Python27\python.exe src/build/vs_toolchain.py update'

No downloadable toolchain found. In order to use your locally installed version of Visual Studio to build Chrome please set DEPOT_TOOLS_WIN_TOOLCHAIN=0.
For details search for DEPOT_TOOLS_WIN_TOOLCHAIN in the instructions at https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md
Traceback (most recent call last):
  File "src/build/vs_toolchain.py", line 559, in <module>
    sys.exit(main())
  File "src/build/vs_toolchain.py", line 555, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "src/build/vs_toolchain.py", line 503, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Python27\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\engine\\src\\build\\win_toolchain.json', '418b3076791776573a815eb298c8aa590307af63']' returned non-zero exit status 1
Hook ''C:\Python27\python.exe' src/build/vs_toolchain.py update' took 41.59 secs
Error: Command 'C:\\Python27\\python.exe src/build/vs_toolchain.py update' returned non-zero exit status 1 in C:\engine

尝试过先 set DEPOT_TOOLS_WIN_TOOLCHAIN=0，再进行同步 但是依然报该错误。

环境是：window7, VS2019, git bash

希望能指导一下，谢谢。

**Comment by danvid** [comment]
你配了环境变量是不是应该重新在启动一下cmd,我也遇到类似的错但设了环境变量就好了

**Comment by zmtzawqlp** [comment]
windows 可以打 安卓的？ ios的？
